### PR TITLE
Fix Issue #69

### PR DESCRIPTION
**Pull request by brunobuzzi**
I tested all inspections and all are working.

### CODE REVIEW

**Comment by jgfoster** [comment]
Could you describe the environment in which you do your development and testing? I need to know the GS/S version and the extent.

One of the goals with Jade is to run in essentially all available GemStone/S configurations and it appears that your submissions are making assumptions about certain classes and methods being present. For example, with the current code I'm unable to log in to a base extent0.dbf with version 3.3.x (PackageOrganizer is an undefined symbol). Other code fails to compile in a 32-bit environment since it doesn't have ANSI exceptions.

**Comment by brunobuzzi** [comment]
GS/S: 3.3.3 - running on VM Player on Windows. How i do get the version of the extent ?
But this is strange !. I do NOT use any GemStone/S specific code. 
The only package that use low level calls is:
Test Browser
imagen

**Comment by jgfoster** [comment]
When you start a stone ('startstone') you can specify a config file that identifies the location of the extent(s) to open. If you do not specify a config file then a default one is used (in $GEMSTONE/data?). In any case, that extent is probably a copy of one of the two extents provided with the product in $GEMSTONE/bin: extent0.dbf or extent0.seaside.dbf. If you are using the Seaside extent then you have things in the repository, such as Monticello, that aren't in the non-Seaside extent. Long-time GemStone customers will have started with an extent before Seaside came along and will not have some things you may take for granted. 

One quick way to tell is to log in as SystemUser (same default password as DataCurator), and see what happens. With the current code I get an error on login because SystemUser does not recognize PackageOrganizer. That is a class added to DataCurator by Seaside. If things don't work as SystemUser, then you are relying on something unique to DataCurator. By default DataCurator should not have anything.

If you are willing to try out a 32-bit Windows environment, then let me know and I'll send you a keyfile (32-bit GemStone does not have a free keyfile included).

**Comment by brunobuzzi** [comment]
James,
You got me here i never imagine that PackageOrganizer was added only to DataCurator by Seaside. 
By it's name i assumed (wrongly) that was a old GemStone class to manage packages.
From now i will log in as SystemUser and check if everything is fine.
Yes, i can try a GemStone 32-bit on Windows and test Jade.

**Pull request merged**
