### PR TITLE
changes to fix issue #97

### PR DESCRIPTION
**Pull request by brunobuzzi**
This PR includes changes on JadeSystemBrowserPresenter>>editCopy and add the method:
JadeAutoTextPresenter3>>copySelection

These two methods avoid the problem of Copy & Paste where all multiple selections were Pasted.
Now if selections size > 1 then enforce the Clipboard with selections last. In [selections] collections all string are the same.
This only happend after double click on a text to highlight.
(Update)
Add fix to multi selection copy paste problem to:
- Method Browser
- Workspace
- Transcript

### CODE REVIEW

**Comment by brunobuzzi** [comment]
This commit fix Ctrl + C with multiple selections but Ctrl + X is not solved.

I will fix Ctrl + X in the next commit or PR.

**Comment by jgfoster** [comment]
I'm investigating this and I like what I see. My immediate concern/question is about the cursor(s). It appears that if there is additional text found then not only is it highlighted, but it adds a blinking cursor to the end of each selection and at the beginning of the method. Do you see that as well.

**Comment by brunobuzzi** [comment]
Yes, i have that behavior too i will try to disable from Scintilla controls.
Anyway if it not possible --> to me is better to have this functionallity (useful to check variable usage inside methods) with the blinking problem (i will try to fix it).

**Comment by brunobuzzi** [comment]
aScintilla hasBlinkingSecondaryCarets: false
 I will add this :)

**Comment by brunobuzzi** [comment]
Check method JadeTextDocument>>defineClass:inPackageNamed:
I have removed it in the last commit (i do not why i got it in my image).
To remove the caret blinking the method is:
JadeTextPresenter>>onViewOpened
...
self view hasBlinkingSecondaryCarets: false.
Check commit:
https://github.com/jgfoster/Jade/pull/129/commits/54d9b509b3c7fa84ecbc5ae106f4d9194783c2be

**Comment by jgfoster** [comment]
I've refactored this PR to use style indicators rather than secondary selections. It is in a branch named 'bruno'. I'll merge it tomorrow unless you have any comments or suggestions.

**Comment by jgfoster** [comment]
By the way, https://github.com/dolphinsmalltalk/Dolphin/pull/509 is required for this to work.

**Comment by brunobuzzi** [comment]
Not working for me.
It seems that JadeAutoTextPresenter3>>updateUI: event is not called/triggered.
If you change createSchematicWiring to:
```
createSchematicWiring
	super createSchematicWiring.
	self 
		when: #autoComplete:startingAt:accept: send: #onAutoComplete:startingAt:accept: to: self;
		when: #leftButtonPressed: send: #onLeftButtonPressed: to: self;
		when: #leftButtonDoubleClicked: send: #selectionChanged: to: self;
		when: #updateUI: send: #updateUI: to: self;
		yourself.
```
Also **selectionChanged** has to be **selectionChanged:** _aMouseEvent_ (the same code - no changes).
If i do this changes the highlight works ok. But IMHO the highlight is too soft (i prefer yellow hightligh).

I will try to change markers setting to be more darker. But we have to find out why updateUI: is **not** working.

**Comment by brunobuzzi** [comment]
After searching a little there is an option in Scintilla to create a more visible indicator using indicator styles.
But ScintillaIndicator styleName: #fullBox is not mapped by Dolphin to a valid ScintillaIndicatorStyle.
I will try to change your:
```
indicators add: (ScintillaIndicator
				styleName: 11
				range: (index to: end) 
				tag: 'secondary selection').
```
To #fullBox instead of 11 but i have to fix the mapping between ScintillaIndicator  and ScintillaIndicatorStyle.

**Comment by brunobuzzi** [comment]
#secondarySelection it can be used insted of 11, but IMHO is not visible enough.

**Comment by brunobuzzi** [comment]
I think with #secondarySelection and alpha: 50 in the ScintillaIndicatorStyle it enough.
I will research how to set 50 to alpha by code (i tested this on Inspector).

**Comment by brunobuzzi** [comment]
To set alpha and configure more ScintillaIndicatorStyle  we have to update views (JadeSystemBrowserPresenter and CodeSourcePresenter) in the View Composer.
Tomorrow i will do it not more time today :)

**Comment by jgfoster** [comment]
Using the latest Dolphin (VM and image, including https://github.com/dolphinsmalltalk/Dolphin/commit/4f56145e2eb83167335d5e7c7e3b16b6b87ad2b0) I'm able to load my 'bruno' branch and it works fine. Are you sure that you have the latest Dolphin? Without it you won't get the #updateUI: to work. As to the color/emphasis, I've been influenced by the other places I've seen this. First is BBEdit and second is Cloud9. Given the extent of other highlighting and coloring in a code workspace edit, we do need to take care to avoid getting too confusing. In any case, I'd be happy to have this configurable.

bbedit

cloud9

I'm going to revise this to reflect the additions to Dolphin that were recently accepted.

**Comment by brunobuzzi** [comment]
I updated the Dolphin VM but like two/three hours ago so should update again.
Tomorrow i will work on this again. And yes configurable emphasis will be the better option.

**Pull request merged**
