### PR TITLE
Fix issues #66 #218 #226 #230

### PR DESCRIPTION
**Pull request by brunobuzzi**
This PR replace JadePreferencesShell with JadePreferencesShell2. 
JadePreferencesShell2 use Dolphin TwinLevelInspector to display options.

If you do not like the change i can roll back. If the change is ok then i will remove JadePreferencesShell. 
One small drawback is that TwinLevelInspector is in Development System package, i can ask @blairmcg to move TwinLevelInspector from Development System to other package to avoid the dependency with Development System.

The idea is to move all Jade Options to the new Shell (for now called JadePreferencesShell2). 
For example:
* Autocompletion options
* Method Browser option (there is a JadeTreeMethodListPresenter that is unused now but it is 100% working -i used this browser instead of the regular Jade Method Browser-). Is like Dolphin Method Explorer.

image

### CODE REVIEW

**Comment by brunobuzzi** [comment]
The User Preferences windows look like this now:
image

**Comment by brunobuzzi** [comment]
Multi Select SUnit Browser
image

**Comment by PeterMoe** [comment]
hi @brunobuzzi ,

i have seen you work on the Jade Preferences, can you have a look at #230 ?

Regards,
Peter

**Comment by brunobuzzi** [comment]
Hi @PeterMoe 

No problem i will add the file out options to new Jade Preferences shell.

**Comment by brunobuzzi** [comment]
The updated method to fileout is: `JadeSystemBrowserPresenter>>fileOutMethodOnPath:` 
image

**Comment by PeterMoe** [comment]
Hi @brunobuzzi,

i have implemented your changes in my "Local development Jade" and it works perfect for me.

Thanx,
Peter

**Pull request merged**
