### PR TITLE
Rewrite tool

### PR DESCRIPTION
**Pull request by brunobuzzi**
@jgfoster this includes the Rewrite Tool and all recent changes you commited.
It also includes:
`JadeSystemBrowserPresenter>>fileOutDictionary` which is referenced but not defined in the lastest commits

Also it seems that `JadeSystemBrowserPresenter>>browseDictionaryReferences` has been lost because is not defined but referenced in `JadeSystemBrowserPresenter>>dictsMenuStrings`

### CODE REVIEW

**Comment by jgfoster** [comment]
`fileOutDictionary` should have been replaced with `fileOutDictionaryOne`. I'll look fo references to the old one. And, good catch on `browseDictionaryReferences` ! I'll see what I can do about that.

**Comment by jgfoster** [comment]
@brunobuzzi , I get an error when I try to deploy (nil does not understand readStream). Are you in a position to investigate?

**Comment by brunobuzzi** [comment]
@jgfoster ok will take a look

**Comment by brunobuzzi** [comment]
@jgfoster the error stack will be very useful

**Comment by jgfoster** [comment]
Unfortunately, the error is sufficiently late in the stripping process so that there is no stack. The deployment XML file simply ends with the following:
```
    ...
    <Global>Inspector</Global> 
  </EmptySystemDictionary>
  <StripCycle>
    <Error class="MessageNotUnderstood">UndefinedObject does not understand #readStream</Error> 
  </StripCycle>
  </Lagoon>
```

**Comment by brunobuzzi** [comment]
Ok no problem i will try to deploy myself

**Comment by jgfoster** [comment]
As a hint, adding #'readStream' to UndefinedObject changes the error to the following:
```
<Error class="STBError">STBFiler - Input stream not in !STL format</Error>
```

**Comment by brunobuzzi** [comment]
Ok, i was able to reproduce the problem.
I will take a look. If i remove some strippe options it produce the .EXE. 
Something is being removed and produce the error. Tomorrow i will research further.

**Comment by brunobuzzi** [comment]
More info:
Step 4) Remove Redudant resources is the culprit.

**Comment by brunobuzzi** [comment]
@jgfoster 
Fixed !!! i will send the PR now.

The problem was a unused Shell resource that was pointing to an non existing Presenter resource (because all resources are defined in subclasses). After deleting the unused Shell resource you can deploy without problems.

So when the stripper try do build the unused Shell the ResourceIdentifier>>resource was nil.

Maybe a Dolphin Stripper bug (when i have time will build a TestCase for Blair)

**Pull request merged**
